### ISSUE TITLE
What is namePrefix used for?

### ISSUE THREAD

**Issue by denizdogan** [lundbird/KustomizeTutorial#1]
I've noticed the value `namePrefix: prod-` in `./after/overlays/prod/kustomization.yaml`, but it's not used anywhere else and it's not explained in the tutorial. Is this a leftover from a previous version of the tutorial? Is it used at all? Thanks in advance.

**Comment by lundbird** [comment]
The example is there to give an example of kustomize directives that are worth knowing.

You can get an idea of what namePrefix does by building the kustomize and viewing the resultant manifests. The namePrefix directive just adds that text as a prefix to your resources such as deployment, configmap, service, ingress, ect. It can be useful when deploying slight variations of an app to the same namespace.

example
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/README.md

**Comment by denizdogan** [comment]
Thank you for the explanation! Appreciate the tutorial.
